# FIXME use master
ARG BASEIMAGE=local/ojs:3_1_2-4

FROM $BASEIMAGE

LABEL maintainer="Public Knowledge Project <marc.bria@gmail.com>"

# add debugger (xdebug)
RUN apk add php7-xdebug --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ && \
  printf 'zend_extension=/usr/lib/php7/modules/xdebug.so\n\
xdebug.coverage_enable=0\n\
xdebug.remote_enable=1\n\
xdebug.default_enable=1\n\
;xdebug.remote_connect_back=1\n\
xdebug.remote_host=172.23.0.1\n\
xdebug.remote_port=9000\n\
xdebug.remote_handler=dbgp\n\
xdebug.remote_log=/tmp/xdebug.log\n\
xdebug.remote_autostart=1\n' >> /etc/php7/php.ini && \
  php -r "echo 'xdebug extension is', (extension_loaded('xdebug') ? '' : 'non '), 'loaded';"
#  \
#xdebug.idekey=eclipse-xdebug \

#https://github.com/martomo/SublimeTextXdebug/issues/162
# DO NOT EXPOSE PORT
#EXPOSE 9000
